export const LANGUAGE_ENGLISH = 'LANGUAGE_ENGLISH';
export const LANGUAGE_ESPANOL = 'LANGUAGE_ESPANOL';
export const LANGUAGE_PORTUGUES = 'LANGUAGE_PORTUGUES';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const OUT_LOGIN = 'OUT_LOGIN';
